### ISSUE TITLE
All kinds of files are missing

### ISSUE THREAD

**Issue by circuitrider** [shahriarhossain/MailChimp.Api.Net#10]
I have no clue wtf went wrong but all kinds of files are missing when syncing and this is not buildable.

Example, ContentTemplate is missing from the Domain/Campaigns folder. Dozens of other examples.

**Comment by circuitrider** [comment]
Oh, they are there. Just not included in the project. How did this build for you?!

**Comment by shahriarhossain** [comment]
I have pushed all files once again including bin, debug etc. Hope you will not get build error any longer.

**Comment by shahriarhossain** [comment]
@circuitrider :  I have pushed all files once again including bin, debug etc. Hope you will not get build error any longer. Let me know if you are still getting issue.
