### ISSUE TITLE
WaitingForActivation

### ISSUE THREAD

**Issue by joiner3710** [shahriarhossain/MailChimp.Api.Net#17]
I dont understand why the i get this message: "WaitingForActivation", when i try to display all mailchimp list.

 I already added the web.config key

<add key="MailChimpApiKey" value="9aa9970c18******e24c544304-us13" />

**Comment by shahriarhossain** [comment]
Could you please show me the code snippet and also screenshot of the error

**Comment by joiner3710** [comment]
the problem was that I did not expect that the task was asynchronous, that message occurred because it had not yet run the task.

Thank you very much for the quick answer.

Regards
