### ISSUE TITLE
Issue while creating campaign and sending mails using MailChimp.Api.Net wrapper

### ISSUE THREAD

**Issue by shaishil** [shahriarhossain/MailChimp.Api.Net#19]
we were able to send the campaign with the help of the wrapper provided by you.
But,while setting the campaign content,we are not able to insert the template along with the email content.Request your help on this.When we send the campaign, the template is not getting reflected along with the email content. 
We are using SetCampaignContentAsync() But when we try attaching the template, we are getting a 'Bad request' error. Seems like there is some issue with the authentication
this is the error I am getting
{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  X-Request-Id: d4f0aa12-fd9f-41aa-aeee-7a0c144a5d08
  Link: https://us13.api.mailchimp.com/schema/3.0/ProblemDetailDocument.json (https://us13.api.mailchimp.com/schema/3.0/ProblemDetailDocument.json%3E) ; rel="describedBy"
  Connection: close
  Date: Wed, 25 May 2016 12:21:12 GMT
  Set-Cookie: _AVESTA_ENVIRONMENT=prod; path=/
  Server: nginx
  Content-Length: 346
  Content-Type: application/problem+json; charset=utf-8
}}

**Comment by shahriarhossain** [comment]
I am not sure how you are attaching the template. In order to upload template first you have to save the whole html in a .txt file and then you have to parse it(you can use the built in parser or you can use your own) and in the end you have to set the result to html property of ContentSetting. Please follow https://github.com/shahriarhossain/MailChimp.Api.Net/wiki/Campaign-Creation-and-Upload-email-template

**Comment by shaishil** [comment]
Actually we don't want to create our templates using code , we just want to use the templates already created in mailchimp by us.We need to create campaign from code provided in the wrapper and attach the already present templates in mailchimp.  So the issue occurs while attaching the already present template to the campaign using SetCampaignContentAsync() method.

**Comment by shahriarhossain** [comment]
So what you are saying is that you first create the template from mailchimp portal and later you want to set it for your campaign, right?

**Comment by shaishil** [comment]
yes right. Our Client has already build the templates in mailchimp. We are just using those templates id to be attached to our campaign using the SetCampaignContentAsync() method.

**Comment by shaishil** [comment]
We are using the wrapper provided by you for attaching the template to a campaign and sending it.
But, we have found an issue with the wrapper code.

namespace MailChimp.Api.Net.Domain.Campaigns
{    public class ContentTemplate
{       public string id { get; set; }
              //One more property needs to be added , chk documentation for details
 }}

The issue with the above piece of code is that when we try to attach a template using the method  SetCampaignContentAsync(string campaign_id, ContentTemplate contentTemplate), it was giving an error because the Mailchimp API expects the template id to be an "Int" but currently this has been defined as "string" in the wrapper code(ContentTemplate).
Request you to please look into this, if this can be fixed

**Comment by shahriarhossain** [comment]
@shaishil : Very good catch. I will make the change and push an update on monday. (am in vacation)

**Comment by shaishil** [comment]
@shahriarhossain : Have you pushed that update for SetCampaignContentAsync method. Actually we are dependent on it.

**Comment by shahriarhossain** [comment]
wait, doing....

**Comment by shahriarhossain** [comment]
@shaishil : I have pushed it on nuget , check out the version 1.2.0.6 and let me know if that solves your issue.

**Comment by shaishil** [comment]
@shahriarhossain : Yes its working. Thank you so much

**Comment by shahriarhossain** [comment]
@shaishil : If you have time please contribute code sample on the [wiki page](https://github.com/shahriarhossain/MailChimp.Api.Net/wiki) showing how you set the campaign with code.

**Comment by shaishil** [comment]
@shahriarhossain : As of now we have used your code only, have not made any modifications on the code end. However will update on wiki if we enhance it anyways
