### ISSUE TITLE
ContentTemplate could not found?

### ISSUE THREAD

**Issue by NomanAhmad** [shahriarhossain/MailChimp.Api.Net#2]
public ContentTemplate template { get; set; } 
ContentTemplate  could not found due to which it shows syntax error?
kindly reply soon ?

**Comment by shahriarhossain** [comment]
When I start investigating the class I found the method SetCampaignContentAsync() cause an error if you pass both ContentSetting and Template at the same time. That make sense cause why would someone send "raw html" and "template" at the same time? I have fixed that issue , hope to push the update next day after testing.

**Comment by shahriarhossain** [comment]
@NomanAhmad  : The issue is solved in version "MailChimp.Api.NET 1.1.7" , check that one. Good luck!
