### ISSUE TITLE
Dynamic offset/count

### ISSUE THREAD

**Issue by nolramlinux** [shahriarhossain/MailChimp.Api.Net#21]
Question: Is there any way to configure offset/count through the Api Wrapper?

Ex:
using MailChimp.Api.Net.Services.Lists;
...
MailChimpList myList = new MailChimpList();
var result = myList.GetAllListsAsync().Result;
...
// result is always <= 10 items
// based on https://usX.api.mailchimp.com/3.0/campaigns?offset=0&count=10

Thanks in advance!

**Comment by nolramlinux** [comment]
My temporary solution was: recompile the DLL adding:
endpoint = String.Format("{0}?offset={1}&count={2}", endpoint, offset, count);

...to the method: GetAllListsAsync() as a parameter (in "MailChimp.Api.Net\Services\Lists\MCListsOverview.cs")

I was wondering if it's something to be incorporated in future releases or there is another option to do it? Thanks!

**Comment by shahriarhossain** [comment]
Nice good catch! You can send me a pull request or alternatively you can also wait one/two days, will update the release in nuget. Thanks.

--- Original Message ---

**Comment by shahriarhossain** [comment]
Issue is fixed, update your nuget package with version 1.2.0.7 . 
Release Note: https://github.com/shahriarhossain/MailChimp.Api.Net/releases/tag/1.2.0.7

**Comment by nolramlinux** [comment]
Great! Thank you for your immediate response, I appreciate your professionalism.

Sincerely,
Marlon Lara

**Comment by shahriarhossain** [comment]
Would be glad if you **_star_** the project.

**Comment by nolramlinux** [comment]
Sure, it's a pleasure.
Regards,
