### ISSUE TITLE
Template missing html

### ISSUE THREAD

**Issue by enkodellc** [shahriarhossain/MailChimp.Api.Net#23]
Thanks for creating this API wrapper. I definitely need to use it for a project and so far been fairly solid. There seems to be a few things missing. Do you have a particular reason why the html field is missing from Templates? I forked the project and will try and add and the submit a PR. There are a few other items I will most likely need to add.  Let me know if you are open to PR's.

**Comment by shahriarhossain** [comment]
@enkodllc: MailChimp did not exposed their v3.0 api all at a same time. If few properties or endpoint are missing then the most probable reason is that those properties were not exposed that time(when I was writing this wrapper), they may have added those property later on.
Yes, I would be happy to have PR on this project.

**Comment by enkodellc** [comment]
@shahriarhossain I think I see the issue, templates have the html property in Create and Update methods but it seems to be missing in the Read method. That seems a bit odd. I will emial them to see what the reason is for this. I see that if I assign the template to a campaign then I can retrieve the content. That seems a bit of a hassle to create a campaign just to retrieve the template's content.

**Comment by enkodellc** [comment]
I added html to the Template in my PR #24 Though this works for Create method it is not currently working in the Get method since as described above it is not open. I did send a request to MailChimp about this issue. I will most likely be creating more PR's as functionality is needed for my project. Thanks!

**Comment by shahriarhossain** [comment]
@enkodellc : Thanks, will check and merge PR #24 tomorrow and push it in nuget as well.

**Comment by enkodellc** [comment]
I cannot believe it. This is MailChimp's response. This makes me want to switch to a different system. 

> Hi there Keith,
> 
> Thanks so much for reaching out to us here in Support. I'm very happy to help with your questions about the HTML property in the API. 
> 
> It sounds to me like what you may be inquiring about is how to use the GET call to retrieve the template content. Just to take a step back here, unfortunately I'm afraid that there wouldn't be a way to make this call using the MailChimp API. Instead, it would be necessary to create a campaign from the template and then GET /campaign/:campaign_id/content. 
> 
> If I'm missing the mark here please don't hesitate to get back in touch and please provide some additional details about what exactly your goals are in this situation. The more we know about what you're hoping to accomplish the better we'll be able to assist. 
> 
> I hope you have a great weekend and thanks again for getting in touch.    
> 
> Thank you,
> Devin

**Comment by shahriarhossain** [comment]
Hey don't get mad, I know its frustrating... Once I back from this vacation I will go through the whole api and point them the pain point. Hope the api team will help us.

--- Original Message ---

**Comment by enkodellc** [comment]
Thanks, I am not mad, of course frustrated. This seems like a rookie mistake or someone missed it during writing the API to me. Something so simple to fix. Maybe it is complicated but having written several API's I find it hard to believe that this single property cannot be included in the "Get". I  guess I should be glad they have some psuedo support.  Let me know what you can do. I have a work around though ugly it will work.

**Comment by enkodellc** [comment]
@shahriarhossain Got another response. Maybe you could add your support request here as well: http://mailchimp.com/contact/feedback/

> Thank you for reaching back out to us. I had a chance to check out your original inquiry along with the workaround solution that Devin provided. Digging in a bit deeper, there unfortunately doesn't appear to be another solution at this time as the /campaign/{campaign_id}/content endpoint is currently the only endpoint available for retrieving content via the API. With that said, I can definitely agree that retrieving template content via the API would be an essential piece. While I wouldn't be able to provide any background as to why this feature has been excluded in the API up to this point, I'd definitely like to see what we can do to have it included in future versions of the API. 
> 
> I've gone ahead and submitted the idea of including a /templates/{template_id}/content endpoint to our developers internally. However, to help get some traction around that idea, I would also recommend submitting that suggestion through our application feedback form. Ideas submitted via the application feedback form go directly to our developers and are the basis for many improvements in our apps. The feedback form can be found at: http://mailchimp.com/contact/feedback/
> 
> Thank you,
> Darren

**Comment by shahriarhossain** [comment]
Its now in **nuget**.  Check the release note [here](https://github.com/shahriarhossain/MailChimp.Api.Net/releases/tag/1.2.0.9).
