### ISSUE TITLE
Naming Convention - Remove vs. Delete - Typo

### ISSUE THREAD

**Issue by enkodellc** [shahriarhossain/MailChimp.Api.Net#29]
@shahriarhossain I see some additional issues as I try to use the API wrapper.  

First I see that you use the verb "Remove" but primarily you use "Delete" I would suggest we refactor the "Remove" to be "Delete" for the sake of consistency.  For example: **RemoveMemberAsync** in MailChimpList.cs. I suggest we call this **DeleteMemberAsync**.

Second issue I see that I didn't catch in MailChimpList.cs is the DeletListMemberAsync function is named incorrectly as it is should be DeleteListMergeFieldAsync.

Third issue is somewhat similar to  I see is that some methods for the List {Member & Merge} are inconsistently named:  For instance in the list you have "AddMember" & "UpdateMember" but the delete is called "DeleteListMember". This again is an inconsistency and should be "DeleteMember"

Fourth is a question. I am adding members to lists which works great but I do not see the option to add "First Name" & "Last Name" Fields. Is this another MailChimp issue that is missing? Or are these fields merge fields that need to be applied and then uploaded?

Please respond and I will create a PR based off your response.  I am in process of testing for 1-3.

**Comment by enkodellc** [comment]
I just found the answer to number 4. on this page: https://devs.mailchimp.com/blog/batch-operations-and-put-in-api-v3-0/  

```
          MailChimp.Api.Net.Domain.Lists.MCMember member = new MailChimp.Api.Net.Domain.Lists.MCMember
              {
                email_address = email,
                email_type = "html",
                language = "English",
                status = SubscriberStatus.subscribed.ToString(),
                status_if_new = SubscriberStatus.subscribed.ToString(),
                merge_fields = new Dictionary<string, object>
                  {
                    { "FIRSTNAME", firstName }, //FNAME
                    { "LASTNAME", lastName }   //LNAME
                  }
              };
```

**Comment by shahriarhossain** [comment]
@enkodellc : Will push it soon to nuget and will inform you once I am done.

**Comment by shahriarhossain** [comment]
Its now in **nuget**.  Check the release note [here](https://github.com/shahriarhossain/MailChimp.Api.Net/releases/tag/1.2.0.9).
