### ISSUE TITLE
Template is not returning HTML values

### ISSUE THREAD

**Issue by roopeshkurian** [shahriarhossain/MailChimp.Api.Net#38]
**Installed versions :** [MailChimp.Api.Net **1.2.0.10**]
## Description

  MailChimpTemplates mTemplate = new MailChimpTemplates();
                    var template = await mTemplate.GetTemplateAsync(model.TemplateId);
In the above coding  template.HTML needs to give us the HTML code of template uploaded. But its showing null. When i checked in Mailchimp I could see the HTML there. 
## Expected behavior

 In the above example I should get HTML value when i use   template.HTML

**Comment by enkodellc** [comment]
@roopeshkurian if you review the MailChimp API they do not offer HTML property in their GET method.  They allow POST / Create and PATCH / Update but no GET, I am thoroughly frustrated by it. Refer to #23 . Please review that for a workaround but also email MailChimp http://mailchimp.com/contact/feedback/ to request it to be added.

**Comment by roopeshkurian** [comment]
Hi,

I requested the feature to MailChimp

Thank you for your help
Roopesh
