### ISSUE TITLE
HTML code is rendering when we open the mail

### ISSUE THREAD

**Issue by roopeshkurian** [shahriarhossain/MailChimp.Api.Net#39]
**Installed versions :** [MailChimp.Api.Net **1.2.0.10**]
## All my emails are printing the HTML code. Its not displaying as an HTML email. Can you please help me?

  It should not print HTML code. But it should display as per the HTML codes.

**Comment by enkodellc** [comment]
This issue was caused because you need to include the proper html tags: html, head, body...

**Comment by enkodellc** [comment]
Here is a guide for the HTML coding when generating new templates:
http://templates.mailchimp.com/development/html/
