### ISSUE TITLE
Issues Response from MailChimp API

### ISSUE THREAD

**Issue by tamlong0205** [shahriarhossain/MailChimp.Api.Net#40]
Hi shahriarhossain,
You had created a great MailChimp.Api.Net. Anything can be worked for me with MVC .NET, but I have  some problems with response from MailChimp API; Example: when I call MailChimpAPI to add a member to exist LIST, a member add to List at 'mailchimp.com' successful but it take a long time and doesn't response anything to my Controller. Anyone can help me to solve this problem.
I had tried a function add multiple member to List, I got the same problem.
After the code run line 14, it cant go to line 15 (line 15 just example for my debug).
This is my code:

```
#region Add a people to List
1                MCMember member = new MCMember()
2               {
3                    email_address = String.Format("my.email@gmail.com"),
4                    email_type = "html",
5                    language = "English",
6                    status = SubscriberStatus.subscribed.ToString(),
7                    merge_fields = new Dictionary<string, object>
8                      {
9                        {"FNAME", "fname"},
10                        {"LNAME", "lname"},
11                        {"CNAME", "company"}
12                      }
13                };
14                var memberAddResult = await mcList.AddMember(member, "5a284f09bf").Result;
15                   int test=0;
                #endregion Add a people to List
```

Thanks

**Comment by enkodellc** [comment]
Try this method **AddMemberAsync** I don't have much experience with MVC but I do know the method should be AddMemberAsync. If it doesn't exist you might want to get the code from the CodeRefactor branch and build it yourself then you can debug locally with that project within your solution:

```
var memberAddResult = myList.AddMemberAsync(member, "5a284f09bf").Result;

if (!result.HasError)
{
  StatusLabel.Text += "<br/>Member Added to List: " + result.Result.id;
}
else
{
  StatusLabel.Text += "<br/>Member Added Error: " + result.ErrorObject.Content;
}
```

**Comment by tamlong0205** [comment]
@enkodellc 
Thank for your reply, I had tried another way to solve my problem. (Not follow the Wrapper of @shahriarhossain )
Anything worked perfect for me.

**Comment by enkodellc** [comment]
If you solved it please post you solution so if others have the same issue we know your solution. The mark the issue as closed.

**Comment by tamlong0205** [comment]
Sorry @shahriarhossain, I dont know I post a reference link are legal or not.

I using this Wapper follow this link, It worked perfect for me:

> https://github.com/brandonseydel/MailChimp.Net

If not legal, please remove this comment.

Thank you,

**Comment by enkodellc** [comment]
Thanks @tamlong0205 I hadn't seen that one yet. I will review it as it looks a bit more refined.
