### ISSUE TITLE
Segments

### ISSUE THREAD

**Issue by strigi** [shahriarhossain/MailChimp.Api.Net#41]
Hi, 

I'm trying to figure out how to create a segment and later use it in a campaign. 
With or w\o MailChimp pro.

**Comment by strigi** [comment]
Any help?

**Comment by enkodellc** [comment]
@strigi The code for the wrapper is fairly simple to add the functionality if you take a look at it. Otherwise you might want to check with https://github.com/brandonseydel/MailChimp.Net as it looks like that wrapper has it already implemented.

**Comment by strigi** [comment]
@enkodellc  Thanks, 
The suggested wrapper only lists segments, not create them.

I'm quite satisfied with your current wrapper, I just don't want to implement other branches on my own.

**Comment by enkodellc** [comment]
Download the CodeRefactor Branch and build that Dll, I included the AddSegment functionality. Did not test, I will leave that up to you.

**Comment by strigi** [comment]
@enkodellc The Refactor branch solution does not compile. 
Missing: Enum\Match.cs

For some reason, on the master branch, there are 3 files missing: 

Services\BatchOperation\BatchOperation.cs
Helper\BundleCreation.cs
Helper\Class1.cs

**Comment by enkodellc** [comment]
Sorry,  Added Match.cs

Those missing files are not needed.
