### ISSUE TITLE
Reports are not giving proper values.

### ISSUE THREAD

**Issue by roopeshkurian** [shahriarhossain/MailChimp.Api.Net#43]
Hello,

**Installed versions :** [MailChimp.Api.Net **1.2.0.9**]
## Description

I have created a campaign and successfully executed the run campaign.  All users got campaign emails.  After that when i am trying to take report of each subscriber its not giving me proper data.

I am trying to run this 

   var x17 = reports.GetUnsubscriberInfoAsync(lstItem.MailChimpID, hashed_email);
But I am getting 'waiting for activation' message. 

Is there any issues?
## Expected behavior

 I should get the activity details of that particular user email

Thank you 
Roopesh

**Comment by shahriarhossain** [comment]
@roopeshkurian : usually "waiting for activation" message indicates that your account is not activated... Make sure it is and then let me know. In the mean while, I will also check for possible reason.

**Comment by roopeshkurian** [comment]
Hi, Its my mistake. I did not put await. Its coding mistake. Now its working fine. When i added await.
