### ISSUE TITLE
API Integration Problems

### ISSUE THREAD

**Issue by fpavlic** [shahriarhossain/MailChimp.Api.Net#54]
Hi,

I've installed MailChimp.Api.NET over nuget, instalation pulled all dependencies as well. Project is working and building fine. However I cannot make any call to MailChimp. MailChimp api key is set in web.config properly. I've also tried some examples from Wiki, they also didn't work.

Here is example:
```
MailChimpList lis = new MailChimpList();

            var member = new MCMember() {
                email_address = model.UserEmail,
                email_type = "html",
                status = SubscriberStatus.subscribed.ToString(),
                language = "English"
            };

            member.merge_fields = new Dictionary<string, object>();
            member.merge_fields.Add("FNAME", model.FirstName.ToTitleCase());
            member.merge_fields.Add("LNAME", model.LastName.ToTitleCase());

            lis.AddMember(member, "539075924f");
```

Any idea where I can look, what I can check ?

Installed versions : MailChimp.Api.NET 1.2.0.10
MVC : 5.2.3
.NET: 4.5

Thanks,
Filip

**Comment by lichcrise** [comment]
Hi Filip
Probaly you set your API Key wrong. Go to your config file and check if its in the appsettings  tag. I made the same misstake, I hope it helps.
