### ISSUE TITLE
Question: Is this code project still active? What is the current status?

### ISSUE THREAD

**Issue by hfloyd** [shahriarhossain/MailChimp.Api.Net#59]
@shahriarhossain ,
There are several unanswered Issues in this project, as well as PRs (from @enkodellc & @cyberjared) which have not been merged, nor commented on. It seems there hasn't been much done here since 2016.

I am starting a new MailChimp integration project for an existing website and am wondering if this is a good library to base my work on. Is this project still actively maintained? Is there a different user fork which is more up-to-date and active? 

Suggestions welcome from all forkers/followers...
Thanks,
Heather

**Comment by enkodellc** [comment]
Heather, I use my fork for a little of MailChimp but ultimately moved to Campaign Monitor and integrated their API for my production project. I think both CM and MC have issues but so far I have been able to get most exactly what I wanted done through Campaign Monitor.

**Comment by hfloyd** [comment]
Thanks, @enkodellc . I did end up forking from your fork, since it seems to be the most updated. I'm not looking to switch from MailChimp right now, since this is an established list, etc. 

Thanks for replying and for your perspective. I'll let you know if I have any PRs for your fork :-)

**Comment by enkodellc** [comment]
Definitely send me any PR's, Just reviewed some of my changes.. Hope they help you as no one ever responded on this repo.

**Comment by hfloyd** [comment]
Great! I appreciate it. Perhaps your fork will become the new official one for this library ;-)

**Comment by enkodellc** [comment]
@hfloyd Merged all the edits!
