### ISSUE TITLE
How to update automation email content?

### ISSUE THREAD

**Issue by Asshen** [shahriarhossain/MailChimp.Api.Net#7]
Dear all,

I need to update the content of automation e-mails. Can anybody give me an example on how to do that?

I am already able to retrieve a list of 10 (why is it limited to 10?) automation e-mails:

```
MailChimp.Api.Net.Services.Automation.MailChimpAutomation automation = new MailChimp.Api.Net.Services.Automation.MailChimpAutomation(); 
MailChimp.Api.Net.Domain.Automations.RootAutomation ra = await automation.GetAutomationListAsync();
```

But how do I retrieve more than 10, and how do I update the content of them?

Thank you.
Kris.

**Comment by Asshen** [comment]
When I try the following, I get an error "400 Bad Request"... any ideas?

```
MailChimpCampaigns campaign = new MailChimpCampaigns();
RootContent rc = await campaign.GetContentAsync( "<content id>" );
ContentSetting sets = new ContentSetting();
sets.html = rc.html.Replace( "hello", "world" );
dynamic res = await campaign.SetCampaignContentAsync( "<content id>", sets );
```

**Comment by shahriarhossain** [comment]
Dear Asshen,
You are receiving 10 automation emails because thats the default one. I will update the method so that you can retrieve x number of mails.

**Comment by shahriarhossain** [comment]
@Asshen : Check the MailChimp.Api.NET 1.2.0.3 version. You can now specify the number of mails you want to retrieve.

**Comment by Asshen** [comment]
Ok, thank you very much for the update :)

However, my bigger problem is how to actually update the email content.
I always get "400 Bad Request".
This is not related to your code. When I use MailChimp.Net (api 2.0) I get the same error.

Maybe you have some example code for updating email content?

Thank you.
Kris.

**Comment by shahriarhossain** [comment]
@Asshen  Kris, Ok, I will put some code snippet and let you know.

**Comment by shahriarhossain** [comment]
@Asshen : So I put a new wiki  [Campaign Creation and Upload email template](https://github.com/shahriarhossain/MailChimp.Api.Net/wiki/Campaign-Creation-and-Upload-email-template).
