### ISSUE TITLE
Custom merge fields

### ISSUE THREAD

**Issue by mattcanty** [shahriarhossain/MailChimp.Api.Net#8]
How are meant to access custom merge fields. The wrapper currently seems to only support FNAME and LNAME.

Expected usage:
`member.merge_fields.SOMETHINGELSE`
or
`member.merge_fields["SOMETHINGELSE"]`

Thanks

**Comment by mattcanty** [comment]
I've mashed up your code base with mine to include this:

`public Dictionary<string,object> merge_fields { get; set; }`

Don't you think this would be a better way of allowing people to access values from a _dynamic_ property bag.

**Comment by shahriarhossain** [comment]
@matthewcanty : Yes, you are right, the current wrapper only supports FName, LName. That seems a good idea to add a dictionary object to access dynamic property bag.

**Comment by circuitrider** [comment]
Oh man bad timing for me on this. I need this feature now but if I fork and implement myself you're just going to have it ready in a couple days I bet...

**Comment by shahriarhossain** [comment]
@matthewcanty : did you work on this part? If so then send a pull req. @circuitrider  was in need of soln. I am running out of time :(

**Comment by mattcanty** [comment]
I had trouble compiling the project locally so just made a bit of a mash
up. If you're able to just change the merge_fields type to
Dictionary<string,object> you'll have what you need.

I won't have access to a computer for a few hours sorry.

**Comment by shahriarhossain** [comment]
@circuitrider : Hey, I have push it on nuget, check MailChimp.Api.NET 1.2.0.4 and let me know if it helps.

**Comment by mattcanty** [comment]
All good. Thanks for implementing this.
